name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: |
          mvn clean package -DskipTests

      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker --version

      - name: Build & Push Docker Image
        run: |
          docker build -t your-dockerhub-username/spring-backend .
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker push your-dockerhub-username/spring-backend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/spring-backend
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 8075:8075 --name backend your-dockerhub-username/spring-backend
